name: Test Workflow

on:
  pull_request:

jobs:
  this-is-a-job-name:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      actions: read
      contents: read
    steps:
      - name: Workflow Telemetry
        uses: erikburt/workflow-telemetry-action@feat/per-core-cpu

      - name: Cehckout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Sleep 5
        run: sleep 5

      - name: Sleep 5
        run: sleep 5

      - name: Sleep 5
        run: sleep 5

      - name: Sleep 5
        run: sleep 5

      - name: Sleep 5
        run: sleep 5
